### ISSUE TITLE
request

### ISSUE THREAD

**Issue by shabaojuan** [Guzaiwang/CE-Net#3]
Can you configure the environment for the next code? For example, torch version? Thank you

**Comment by QingqingWang-1** [comment]
Hi Guzai Wang,
Thanks for opening your code. I also need to know your environment(Cuda version, torch version, python version etc), because I got the following error when running your code under torch0.4. I am not sure whether it is caused by the environment or not.

 warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
/home/wqq/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:1961: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
/home/wqq/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:1006: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/THC/generic/THCTensorMathPairwise.cu line=21 error=59 : device-side assert triggered
Traceback (most recent call last):

  File "<ipython-input-1-b4ec16818231>", line 1, in <module>
    runfile('/home/wqq/qingqwan/MediSeg/CE-Net-master/main.py', wdir='/home/wqq/qingqwan/MediSeg/CE-Net-master')

  File "/home/wqq/anaconda3/envs/pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "/home/wqq/anaconda3/envs/pytorch/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/wqq/qingqwan/MediSeg/CE-Net-master/main.py", line 103, in <module>
    CE_Net_Train()

  File "/home/wqq/qingqwan/MediSeg/CE-Net-master/main.py", line 60, in CE_Net_Train
    train_loss, pred = solver.optimize()

  File "/home/wqq/qingqwan/MediSeg/CE-Net-master/framework.py", line 66, in optimize
    self.optimizer.step()

  File "/home/wqq/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/optim/adam.py", line 100, in step
    denom = exp_avg_sq.sqrt().add_(group['eps'])

RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/THC/generic/THCTensorMathPairwise.cu:21

**Comment by shabaojuan** [comment]
i also met the same question.

**Comment by QingqingWang-1** [comment]
Figure it out! Torch0.4 works. The problem is caused by the loss function. 
It can be solved by changing: a = self.ce_loss(y_pred, y_ce_true)
to: b = self.multi_class_dice_loss(y_prediction, y_true)

**Comment by shabaojuan** [comment]
I succeeded in running according to your method, but it ended after running about thirty epochs. I want to ask you how the result of running is. Thank you very much.

**Comment by Guzaiwang** [comment]
> I succeeded in running according to your method, but it ended after running about thirty epochs. I want to ask you how the result of running is. Thank you very much.

Sorry, in the original implementation, the multi-class dice loss and binary cross entropy loss were separate. When we create this repository, we integrate both of them into a loss function. And the CUDA error (or warning) occurs.   Now, we have modified the loss function. It works.

**Comment by QingqingWang-1** [comment]
> > I succeeded in running according to your method, but it ended after running about thirty epochs. I want to ask you how the result of running is. Thank you very much.
> 
> Sorry, in the original implementation, the multi-class dice loss and binary cross entropy loss were separate. When we create this repository, we integrate both of them into a loss function. And the CUDA error (or warning) occurs. Now, we have modified the loss function. It works.

Many thanks. It works now.

**Comment by shabaojuan** [comment]
Thank you very much for your reply and code. Could you upload the test code? Thank you very much.

**Comment by Altaf-Hussain-AI** [comment]
Hi Guzai Wang,
Thanks for opening your code. i have a question as you have mention that "start the  visdom file before running main.py file. 
i didn't understand what is "visdom" can you please tell me about visdom what is this and how to start it? 
i shall be very thankful to you.

**Comment by howie924** [comment]
> Hi Guzai Wang,
> Thanks for opening your code. i have a question as you have mention that "start the visdom file before running main.py file.
> i didn't understand what is "visdom" can you please tell me about visdom what is this and how to start it?
> i shall be very thankful to you.

visdom is a tool that can plot errors vs epoches that helps you visually see the training phase, you actually do not need to use the visdom part.

**Comment by Altaf-Hussain-AI** [comment]
Thanks you so much for your kind response



发自我的iPhone


------------------ Original ------------------

**Comment by bai101315** [comment]
请问那个test_center是测试代码吗？还是说您没有把test代码上传到GitHub上？

**Comment by nobody2231** [comment]
> 请问那个test_center是测试代码吗？还是说您没有把test代码上传到GitHub上？

能把test_center文件分享一下吗？
